version: '3'

services:

  mysql_we:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: we
      MYSQL_PASSWORD: we
      MYSQL_DATABASE: we
    volumes:
      - webdev_we:/var/lib/mysql

  wordpress_we:
    depends_on:
      - mysql_we
    build: ./
    image: wordpress_we
    restart: always
    ports:
      - 8080:80
    links:
      - mysql_we:mysql_we
    volumes:
      - ./theme:/var/www/html/wp-content/themes/we
      - ./plugin:/var/www/html/wp-content/plugins/we
    environment:
      WORDPRESS_DB_HOST: mysql_we:3306
      WORDPRESS_DB_USER: we
      WORDPRESS_DB_PASSWORD: we
      WORDPRESS_DB_NAME: we

volumes:
  webdev_we:
    external: true
